export { default as InputText } from './InputText'
export { default as InputSearch } from './InputSearch'
export { default as InputSelect } from './InputSelect'
export { default as Pagination } from './Pagination'
export { default as ButtonCustom } from './Button'
export { default as ColorPicker } from './InputColor'
export { default as TableView } from './Table'
